const color = {
  contentBackground: "#333",
  contentTitle: "#FFF",
  contentSubtitle: "#FFB300",
  contentText: "#FFF",
  menuBackgound: "#222",
  menuHamburguerIcon: "#FFF",
  menuLinksHover: "#999",
  menuLinksIconsHover: "#999",
  menuLinks: "#FFF",
  menuLinksIcons: "#FFF",
  headerArrow: "#555",
  carouselTitle: "#FFF",
  carouselArrow: "#FFF",
  carouselArrowHover: "#555",
  carouselArrowBackgroundHover: "#FFF",
  cardBackground: "#444",
  cardTitle: "#FFF",
  cardFavoriteIcon: "#FFF",
  cardFavoriteIconHover: "#FF0000",
  cardFavoriteIconActive: "#FF0000",
  cardMidiaDescriptionBackground: "#666",
  cardAuthorName: "#999",
  cardLength: "#999",
  cardMidiaIcon: "#FFF",
  cardType: "#FFF",
};

export default color;
