const CONTENT: any = {
  1: {
    title: "A vida interior e a oração",
    url: "https://generate.focolare.org/wp-content/uploads/2022/09/SCM-VD-20220911-2660Mpt.mp4",
    description:
      "Margaret Karram, no Ano Ideal 2022-23 dedicado ao tema da oração, oferece uma experiência e uma visão da oração e da vida interior do Carisma na reunião dos Delegados da Obra de Maria.",
    author: "KARRAM MARGARET",
    data: "11/09/2022",
    type: "VIDEO",
    length: "32",
    tags: ["AMARELO"],
  },
  2: {
    title: "Maria e a Obra de Maria",
    url: "https://generate.focolare.org/wp-content/uploads/2020/06/gen-285-video-pt.mp4",
    description:
      "Chiara explica aos popetti (crianças) sobre a importância de Maria Desolada na vida do Ideal e porque o Movimento é chamado de Obra de Maria.",
    author: "LUBICH CHIARA",
    data: "13/08/1963",
    type: "VIDEO",
    length: "3",
    tags: ["DESOLADA", "IDEAL", "OBRA DE MARIA"],
  },
  3: {
    title: "Ser Outra Maria",
    url: "https://generate.focolare.org/wp-content/uploads/2020/06/gen-286-video-pt.mp4",
    description:
      "Portanto, logicamente meu designo aqui na Terra é ser outra pequena Maria que, sendo a primeira e como alguém disse: tomar o lugar de Maria, isso também está certo, faço as vezes de Maria, isso mesmo…",
    author: "LUBICH CHIARA",
    data: "02/06/1976",
    type: "VIDEO",
    length: "8",
    tags: ["CHIARA", "DISÍGNÍO", "MARIA", "PEQUENA", "VIGARIA"],
  },
  4: {
    title: "Maria, condutora da humanidade",
    url: "https://generate.focolare.org/wp-content/uploads/2021/04/2-1.-Maria-Condottiera.mp4",
    description:
      "Neste vídeo apresentado no Congresso das Unidades Arco-Íris e secretarias JPMU de 2021, Chiara apresenta Maria como uma grande contestadora e repercorre as fases da sua vida.",
    author: "LUBICH CHIARA",
    data: "16/07/1969",
    type: "VIDEO",
    length: "15",
    tags: [
      "2021",
      "CONDUTORA",
      "CONGRESSO",
      "CONTESTADORA",
      "HUMANIDADE",
      "MARIA",
      "SECRETARIA JPMU",
      "SIM",
      "UAI-SJPMU2021",
      "UNIDADE ARCO-ÍRIS",
    ],
  },
  5: {
    title: "Tutorial GENerate",
    url: "https://generate.focolare.org/wp-content/uploads/2022/02/Tutorial-GENerate-Portughese.mp4",
    description:
      "Um tutorial GENerate registrado em direta para permitir aos gen e assistentes de conhecer o funcionamento da plataforma e terem acesso com facilidade aos materiais que são disponíveis.",
    author: null,
    data: "19/02/2022",
    type: "VIDEO",
    length: "47",
    tags: null,
  },
  6: {
    title: "Frutos da vontade de Deus",
    url: "https://generate.focolare.org/wp-content/uploads/2020/07/csc-0224m3-video.mp4",
    description: "A oração e em particular o rosário, como eu o rezo: significado dos vários mistérios.",
    author: "LUBICH CHIARA",
    data: "20/01/1981",
    type: "VIDEO",
    length: "17",
    tags: ["MISTÉRIOS", "MODERNA", "ORAÇÃO", "PAPA", "ROSÁRIO"],
  },
  7: {
    title: "Maria doa a vida",
    url: "https://generate.focolare.org/wp-content/uploads/2020/06/gen-290-video-pt.mp4",
    description:
      "Maria gera sempre vida. O Movimento gera uma geração nova (Gen), uma sociedade nova através de Humanidade Nova, as famílias através de Famílias Novas. Gerar e renovar é característico de Maria.",
    author: "LUBICH CHIARA",
    data: "20/04/1978",
    type: "VIDEO",
    length: "2",
    tags: ["DOM", "FAMÍLIA", "GERAR", "HUMANIDADE", "MARIA", "RENOVAMENTO", "VIDA"],
  },
  8: {
    title: "Fazer justiça - Maria sinal de contradição",
    url: "https://generate.focolare.org/wp-content/uploads/2020/07/csc-0045m-video.mp4",
    description:
      "O Movimento Gen é uma revolução do amor sobrenatural, seu objetivo é fazer justiça. O mundo de hoje desconhece Maria, especialmente os jovens; a Imaculada é um sinal de contradição e os gen vão contra a corrente, até que os jovens recuperem a sentido da pureza. Esta é a tarefa que Deus tem pensado para Maria.",
    author: "LUBICH CHIARA",
    data: "29/12/1972",
    type: "VIDEO",
    length: "23",
    tags: [
      "CONTRACORRENTE",
      "DISÍGNÍO",
      "FAZER JUSTIÇA",
      "JUSTIÇA",
      "MARIA",
      "MOVIMENTO GEN",
      "OPERAÇÃO ÁFRICA",
      "REVOLUÇÃO",
    ],
  },
  9: {
    title: "Perder como Maria",
    url: "https://generate.focolare.org/wp-content/uploads/2020/06/gen-291-video-pt.mp4",
    description:
      "Como Maria, saber perder Jesus em meio para amar os outros católicos, as outras denominações cristãs, as pessoas de outras religiões.",
    author: "LUBICH CHIARA",
    data: "02/01/1982",
    type: "VIDEO",
    length: "6",
    tags: ["DIÁLOGO", "ECUMENISMO", "JESUS NO MEIO", "MARIA", "PERDER"],
  },
  10: {
    title: "EBA2022_O amor cura a Criação Parte 1",
    url: "https://generate.focolare.org/wp-content/uploads/2022/11/TEMATICA-NINO-PT1-SBA-22-FINALE.mp4",
    description:
      "Nino Puglisi, investigador químico e membro da Comissão EcoOne para a Inundação da Ecologia, juntamente com Bianca Carvalho, uma cientista biomédica do Brasil e Gen 2, oferecem um olhar sobre as nossas relações com a Criação. Ajudam-nos a alargar o nosso olhar e a tentar um “abraço cósmico” que absorve não só as nossas relações com outras criaturas humanas, mas também com criaturas animais e o resto em natureza inanimada que, juntamente connosco, partilham esta extraordinária viagem que é a existência.",
    author: "CENTROS GEN2 - JPMU",
    data: "12/08/2022",
    type: "VIDEO",
    length: "49",
    tags: [
      "CRIAÇÃO",
      "CRIADO",
      "ECOLOGIA",
      "ESCOLA",
      "ESCOLA ASSISTENTES",
      "ESCOLA DE BRANCOS",
      "ESCOLA GEN",
      "NATUREZA",
      "VERDE",
    ],
  },
  11: {
    title: "EBA2022_O amor cura os relacionamentos Parte 1",
    url: "https://generate.focolare.org/wp-content/uploads/2022/11/TEMATICA-ELISABETH-PT1-SBA-22-FINALE.mp4",
    description:
      "Elisabeth Reichel, psiquiatra-psicoterapeuta e Ana Heloísa Romão, arquiteta, Gen 2 do Brasil, ajudam-nos a explorar mais sobre como ligar o conceito de doação e de dar vida com a ideia da própria liberdade e como ela se apresenta na vida quotidiana normal. Como é possível viver o amor, o abandono total a Deus e ao próximo e, ao mesmo tempo, realizar-se como pessoa. O que significa para nós crescer e amadurecer como indivíduos na e com a vida da Unidade.",
    author: ["CENTROS GEN2 - JPMU", "ELISABETH REICHEL"],
    data: "16/08/2022",
    type: "VIDEO",
    length: "46",
    tags: ["ACOMPANHAMENTO", "ESCOLA", "ESCOLA ASSISTENTES", "ESCOLA DE BRANCOS", "ESCOLA GEN", "PSICOLOGIA"],
  },
  12: {
    title: "EBA2022_O amor cura e acompanha Parte 1",
    url: "https://generate.focolare.org/wp-content/uploads/2022/11/TEMATICA-ROBERTO-1-SBA-22-FINALE.mp4",
    description:
      "É com este tema liderado por Roberto Almada, Mariane Berti e Jarsan Lavor, dois géneros do Brasil, que podemos aprofundar a nossa compreensão do valor do acompanhamento. O que é o acompanhamento? Existe uma ética de acompanhamento? Como podemos ser de ajuda através de uma boa entrevista? A dinâmica responde a estas questões e desenvolve as várias etapas do acompanhamento. A conclusão refere-se a um texto de Chiara de '49.",
    author: "CENTROS GEN2 - JPMU",
    data: "18/08/2022",
    type: "VIDEO",
    length: "30",
    tags: ["ACOMPANHAMENTO", "ESCOLA", "ESCOLA ASSISTENTES", "ESCOLA DE BRANCOS", "ESCOLA GEN", "RELACIONAMENTO"],
  },
  13: {
    title: "EBA2022_O amor cura as nossas fragilidades Parte 1",
    url: "https://generate.focolare.org/wp-content/uploads/2022/10/TEMATICA-TOMASSO-SBA-22-FINALE.mp4",
    description:
      "Somos todos frágeis. A fragilidade é parte da nossa condição humana. Por vezes temos sido feridos no amor, nas relações, na confiança, e as feridas sangram. O que acontece quando corajosamente tocamos e deixamos Jesus tocar-nos? A mulher com a hemorragia, mencionada no evangelho de Marcos, lidera o caminho nesta viagem. Necessidade de amor, fé e salvação são as palavras que dão ritmo a este tema. Um discurso sobre fragilidade porque o nosso Deus é também “um Deus frágil”.",
    author: ["BERTOLASI TOMMASO", "CENTROS GEN2 - JPMU"],
    data: "10/08/2022",
    type: "VIDEO",
    length: "31",
    tags: ["ESCOLA", "ESCOLA ASSISTENTES", "ESCOLA DE BRANCOS", "ESCOLA GEN"],
  },
  14: {
    title: "EBA2022_O amor cura o olhar sobre o outro",
    url: "https://generate.focolare.org/wp-content/uploads/2022/11/TEMATICA-KASIA-SBA-22-FINALE.mp4",
    description:
      "Kasia Wasiutynska, especialista em teologia espiritual, e Marina Barbosa, química, Gen 2 do Brasil oferecem uma leitura do texto do Paraíso '49 'Olhando para todas as flores', partindo de um olhar sobre nós próprios, sobre a realidade e um sobre o outro, e, numa dinâmica de comunhão, compreendendo como aplicar a visão que Clare oferece neste texto à vida concreta da unidade.",
    author: "CENTROS GEN2 - JPMU",
    data: "15/08/2022",
    type: "VIDEO",
    length: "62",
    tags: [
      "ESCOLA",
      "ESCOLA ASSISTENTES",
      "ESCOLA DE BRANCOS",
      "ESCOLA GEN",
      "ESPIRITUALIDADE",
      "PARAÍSO",
      "RELACIONAMENTO COM DEUS",
    ],
  },
  15: {
    title: "EBA2022_O amor cura a Criação Parte 2",
    url: "https://generate.focolare.org/wp-content/uploads/2022/11/TEMATICA-NINO-PT2-SBA-22-FINALE.mp4",
    description:
      "Nino Puglisi, investigador químico e membro da Comissão EcoOne para a Inundação da Ecologia, juntamente com Bianca Carvalho, uma cientista biomédica do Brasil e Gen 2, oferecem um olhar sobre as nossas relações com a Criação. Ajudam-nos a alargar o nosso olhar e a tentar um “abraço cósmico” que absorve não só as nossas relações com outras criaturas humanas, mas também com criaturas animais e o resto em natureza inanimada que, juntamente connosco, partilham esta extraordinária viagem que é a existência.",
    author: "CENTROS GEN2 - JPMU",
    data: "12/08/2022",
    type: "VIDEO",
    length: "49",
    tags: [
      "CRIAÇÃO",
      "CRIADO",
      "ECOLOGIA",
      "ESCOLA",
      "ESCOLA ASSISTENTES",
      "ESCOLA DE BRANCOS",
      "ESCOLA GEN",
      "NATUREZA",
      "VERDE",
    ],
  },
  16: {
    title: "EBA2022_O amor cura os relacionamentos Parte 2",
    url: "https://generate.focolare.org/wp-content/uploads/2022/11/TEMATICA-ELISABETH-PT2-SBA-22-FINALE.mp4",
    description:
      "Elisabeth Reichel, psiquiatra-psicoterapeuta e Ana Heloísa Romão, arquiteta, Gen 2 do Brasil, ajudam-nos a explorar mais sobre como ligar o conceito de doação e de dar vida com a ideia da própria liberdade e como ela se apresenta na vida quotidiana normal. Como é possível viver o amor, o abandono total a Deus e ao próximo e, ao mesmo tempo, realizar-se como pessoa. O que significa para nós crescer e amadurecer como indivíduos na e com a vida da Unidade.",
    author: ["CENTROS GEN2 - JPMU", "ELISABETH REICHEL"],
    data: "16/08/2022",
    type: "VIDEO",
    length: "92",
    tags: ["ACOMPANHAMENTO", "ESCOLA", "ESCOLA ASSISTENTES", "ESCOLA DE BRANCOS", "ESCOLA GEN", "PSICOLOGIA"],
  },
  17: {
    title: "EBA2022_O amor cura e acompanha Parte 2",
    url: "https://generate.focolare.org/wp-content/uploads/2022/11/TEMATICA-ROBERTO-2-SBA-22-FINALE.mp4",
    description:
      "É com este tema liderado por Roberto Almada, Mariane Berti e Jarsan Lavor, dois géneros do Brasil, que podemos aprofundar a nossa compreensão do valor do acompanhamento. O que é o acompanhamento? Existe uma ética de acompanhamento? Como podemos ser de ajuda através de uma boa entrevista? A dinâmica responde a estas questões e desenvolve as várias etapas do acompanhamento. A conclusão refere-se a um texto de Chiara de '49.",
    author: "CENTROS GEN2 - JPMU",
    data: "18/08/2022",
    type: "VIDEO",
    length: "47",
    tags: ["ESCOLA", "ESCOLA ASSISTENTES", "ESCOLA DE BRANCOS", "ESCOLA GEN"],
  },
  18: {
    title: "Controvento",
    url: "https://generate.focolare.org/wp-content/uploads/2020/12/Controvento.mp3",
    description: "Genfest 2000 – Uma onda de “Luz”",
    author: "GENFEST 2000",
    data: "03/12/2020",
    type: "AUDIO",
    length: "4",
    tags: null,
  },
  19: {
    title: "Sincronizzati",
    url: "https://generate.focolare.org/wp-content/uploads/2020/12/Sincronizzati.mp3",
    description: "Genfest 2000 – Uma onda de “Luz”",
    author: "GENFEST 2000",
    data: "03/12/2020",
    type: "AUDIO",
    length: "3",
    tags: null,
  },
  20: {
    title: "Hold on",
    url: "https://generate.focolare.org/wp-content/uploads/2020/12/Hold-on.mp3",
    description: "Genfest 2000 – Uma onda de “Luz”",
    author: "GENFEST 2000",
    data: "03/12/2020",
    type: "AUDIO",
    length: "4",
    tags: null,
  },
  21: {
    title: "Facts not words",
    url: "https://generate.focolare.org/wp-content/uploads/2020/12/Facts-not-words.mp3",
    description: "Genfest 2000 – Uma onda de “Luz”",
    author: "GENFEST 2000",
    data: "03/12/2020",
    type: "AUDIO",
    length: "4",
    tags: null,
  },
  22: {
    title: "Un cielo da scoprire",
    url: "https://generate.focolare.org/wp-content/uploads/2020/12/un-cielo-da-scoprire.mp3",
    description: "Genfest 2000 – Uma onda de “Luz”",
    author: "GENFEST 2000",
    data: "03/12/2020",
    type: "AUDIO",
    length: "4",
    tags: null,
  },
  23: {
    title: "Basta una sonrisa",
    url: "https://generate.focolare.org/wp-content/uploads/2020/12/Basta-un-sonrisa.mp3",
    description: "Genfest 2000 – Uma onda de “Luz”",
    author: "GENFEST 2000",
    data: "03/12/2020",
    type: "AUDIO",
    length: "5",
    tags: null,
  },
  24: {
    title: "Now and Here",
    url: "https://generate.focolare.org/wp-content/uploads/2020/12/Now-and-Here.mp3",
    description: "Genfest 2000 – Uma onda de “Luz”",
    author: "GENFEST 2000",
    data: "03/12/2020",
    type: "AUDIO",
    length: "3",
    tags: null,
  },
  25: {
    title: "Fill the Void",
    url: "https://generate.focolare.org/wp-content/uploads/2020/12/Fill-the-Void.mp3",
    description: "Genfest 2000 – Uma onda de “Luz”",
    author: "GENFEST 2000",
    data: "03/12/2020",
    type: "AUDIO",
    length: "4",
    tags: null,
  },
};

export default CONTENT;
